apiVersion: v1
kind: ReplicationController
metadata: #this section is for the Replication Controller definition
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec: 
  template:
    metadata: #this section is for the Pod definition
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3